from flask import Blueprint, render_template, redirect, request, url_for, current_app, jsonify
from werkzeug.security import generate_password_hash, check_password_hash
from flask_jwt_extended import create_access_token, decode_token
from flask_dance.contrib.google import make_google_blueprint, google
from app.models import User
from app import db
from app.utils.email import send_verification_email
import random
from datetime import datetime, timedelta, timezone
import os


google_bp = make_google_blueprint(
    client_id=os.environ.get('GOOGLE_CLIENT_ID'),
    client_secret=os.environ.get('GOOGLE_CLIENT_SECRET'),
    scope=["openid", "https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"],
    redirect_url="/api/auth/google/callback"
)

auth = Blueprint('auth',__name__)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    data = request.get_json() or {}
    print(data)

    required_fields = ['email', 'password']
    for field in required_fields:
        if field not in data:
            return jsonify({'error': f'Missing required field: {field}'}), 400

    if User.query.filter_by(email=data['email']).first():
        return jsonify({'error': 'Email address already registered'}), 400

    email = data['email'].strip()
   

    hashed_password = generate_password_hash(data['password'], method='pbkdf2:sha256')

    otp_code = f"{random.randint(100000, 999999)}"
    reg_claims = {
        "email": email,
        "password_hash": hashed_password,
        "role": data.get('role', 'parent'),
        "otp": otp_code,
        "action": "registration_pending"
    }
    
    # This token holds our temporary user data securely for exactly 15 minutes
    registration_token = create_access_token(
        identity=email, 
        expires_delta=timedelta(minutes=15), 
        additional_claims=reg_claims
    )

    email_sent = send_verification_email(email, otp_code)

    if not email_sent:
        return jsonify({'error': 'Mailing system offline. Please try again later.'}), 500
        
    # Pass the registration token back to the frontend so it can hold onto it
    return jsonify({
        'message': 'Verification code sent!',
        'reg_token': registration_token
    }), 201


@auth.route('/verify-code', methods=["POST"])
def verify_code():
    data = request.get_json() or {}
    # email = data.get('email', '').strip()
    submitted_code = data.get('code', '').strip()
    registration_token = data.get('reg_token', '').strip()
    
        
    try:
        # Decode the token. If 15 minutes passed, it automatically throws an expired exception!
        decoded_claims = decode_token(registration_token)
        claims = decoded_claims.get('extra_claims', {})
        print("claims", claims)
        print("point 3")
        # Verify this token was actually generated by our signup route

        if not claims or 'action' not in claims:
            claims = decoded_claims
        if claims.get('action') != 'registration_pending':
            print("point 4")
            return jsonify({'error': 'Invalid token context.'}), 400
            
        # ❌ Check if the code they typed matches the secret code encrypted inside the token
        if claims.get('otp') != submitted_code:
            print("point 5")
            return jsonify({'error': 'Incorrect verification code. Try again.'}), 400    
        
        email = claims.get('email')
        print(email, submitted_code, registration_token)
        if not email or not submitted_code:
            print("point 1")
            return jsonify({'error': 'Missing email or verification code'}), 400
        
        if not submitted_code or not registration_token:
            print("point 2")
            return jsonify({'error': 'Missing verification code or registration token.'}), 400 
        
        user = User.query.filter_by(email=email).first()
            
        if user:
            return jsonify({'message': 'Account is already verified. You can log in.'}), 200
    
        # 🎉 MATCH CONFIRMED! Create the user in our real database now
        username_extracted = email.split('@')[0]
        new_user = User(
            username=username_extracted,
            email=email,
            password_hash=claims.get('password_hash'),
            role=claims.get('role'),
            # parent_name= username_extracted
        )
        
        db.session.add(new_user)
        db.session.commit()
        
        return jsonify({'message': 'Signup complete! Your account is officially active.'}), 200
        
    except Exception as e:
        # Fires automatically if token signature fails or is expired
        print("point 7")
        return jsonify({'error': 'Your verification session has expired. Please sign up again.'}), 400
    
@auth.route('/login', methods=['POST'])
def login():
    data = request.get_json() or {}

    print(data)
    email = data['email']
    password = data['password']
    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password_hash, password):
        return jsonify({'error': 'Invalid email or password'}), 401
    
    additional_claims = {"role": user.role}
    access_token = create_access_token(identity=str(user.id), additional_claims=additional_claims)
    return jsonify({
        'message': 'Login successful!',
        'token': access_token,
        'user': {
            'id': user.id,
            'username': user.username,
            'email': user.email,
            'role': user.role,
            # 'parent_name': user.parent_name
        }
    }), 200
@auth.route('/forgot-password', methods=["POST"])
def forgot_password():
    data = request.get_json() or {}

    email = data.get('email', '').strip()
    if not email:
        return jsonify({'error': 'Missing email'}), 400

    user = User.query.filter_by(email=email).first()
    if not user:
        return jsonify({'error': 'An account with this email does not exist'}), 404

    otp_code = f"{random.randint(100000, 999999)}"
    reg_claims = {
        "email": email,
        "otp": otp_code,
        "action": "changing password"
    }
    registration_token = create_access_token(
        identity=email, 
        expires_delta=timedelta(minutes=15), 
        additional_claims=reg_claims
    )

    email_sent = send_verification_email(email, otp_code)

    if not email_sent:
        return jsonify({'error': 'Mailing system offline. Please try again later.'}), 500
        
    # Pass the registration token back to the frontend so it can hold onto it
    return jsonify({
        'message': 'Verification code sent!',
        'reg_token': registration_token
    }), 201


@auth.route('/reset-password', methods=["POST"])
def reset_password():
    data = request.get_json() or {}
    submitted_code = data.get('code', '').strip()
    registration_token = data.get('reg_token', '').strip()
    new_password = data.get('new_password')
    try:
        decoded_claims = decode_token(registration_token)
        claims = decoded_claims.get('extra_claims', {})

        if not claims or 'action' not in claims:
            claims = decoded_claims
        if claims.get('action') != 'changing password':
            print("point 4")
            return jsonify({'error': 'Invalid token context.'}), 400
            
        if claims.get('otp') != submitted_code:
            print("point 5")
            return jsonify({'error': 'Incorrect verification code. Try again.'}), 400    
        
        email = claims.get('email')
        print(email, submitted_code, registration_token)
        if not email or not submitted_code:
            print("point 1")
            return jsonify({'error': 'Missing email or verification code'}), 400
        
        if not submitted_code or not registration_token:
            print("point 2")
            return jsonify({'error': 'Missing verification code or registration token.'}), 400 
        if not new_password:
            print("point 13")
            return jsonify({'error': 'Missing password'}), 400
        
        user = User.query.filter_by(email=email).first()
        
        if not user:
            return jsonify({'error': 'An account with this email does not exist'}), 404
    
        
        user.password_hash = generate_password_hash(new_password, method='pbkdf2:sha256')
        db.session.commit()
        
        return jsonify({'message': 'Your password has been successfully changed!. Log in'}), 200
        
    except Exception as e:
        # Fires automatically if token signature fails or is expired
        print("point 7")
        return jsonify({'error': 'Your verification session has expired. Please sign up again.'}), 400
    
    
#Oauth
@auth.route('/google/callback')
def google_callback():
    if not google.authorized:
        return redirect(url_for('google.login'))
    
    resp = google.get("/oauth2/v2/userinfo")
    if not resp.ok:
        return jsonify({'error': 'Failed to fetch user info from Google'}), 400
    
    info = resp.json()
    email = info['email']
    name = info.get('name', email.split('@')[0])

    # Check if user exists
    user = User.query.filter_by(email=email).first()
    
    if not user:
        # Create new account
        user = User(
            email=email,
            username=name,
            role='parent',
            password_hash= generate_password_hash("blah@ihc#1", method='pbkdf2:sha256'), # random password
        )
        db.session.add(user)
        db.session.commit()

    # Generate JWT
    token = create_access_token(
        identity=str(user.id),
        additional_claims={"role": user.role}
    )
    
    # Redirect to frontend with token
    frontend_url = os.environ.get('FRONTEND_URL', 'https://brightminds-tutors.vercel.app')
    return redirect(f"{frontend_url}/dashboard.html?token={token}")