"""removed session_type amd renamed bio to teaching experience on the tutor applications table

Revision ID: 060841f5bb57
Revises: 9d0fa521a088
Create Date: 2026-06-23 11:15:48.803952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060841f5bb57'
down_revision = '9d0fa521a088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teaching_experience', sa.Text(), nullable=False))
        batch_op.drop_column('session_type')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('session_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('teaching_experience')

    # ### end Alembic commands ###
