"""changed field name from comment to feedback in reviews

Revision ID: 0e3109ecae39
Revises: 3521ecb54fa2
Create Date: 2026-06-11 12:06:15.241443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3109ecae39'
down_revision = '3521ecb54fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
