"""removed is_approved from tutor profiles table

Revision ID: 3d3bc4080eb9
Revises: 788ffb6d849f
Create Date: 2026-06-22 20:14:45.104023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3bc4080eb9'
down_revision = '788ffb6d849f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
