"""put on cascade dele on tutor applications

Revision ID: 6c6c1733bdac
Revises: 2d547440167b
Create Date: 2026-06-25 09:45:58.811135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6c1733bdac'
down_revision = '2d547440167b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tutor_applications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tutor_applications_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
