"""added notes to bookings table and disabilities to student table

Revision ID: 788ffb6d849f
Revises: f289876f7e61
Create Date: 2026-06-22 11:48:19.626811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788ffb6d849f'
down_revision = 'f289876f7e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('disabilities_or_notes')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabilities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('disabilities')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabilities_or_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
