"""removed institution field form tutor application

Revision ID: 92e687837054
Revises: 060841f5bb57
Create Date: 2026-06-23 11:29:53.987938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e687837054'
down_revision = '060841f5bb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.drop_column('institution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.VARCHAR(length=150), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
