"""added level taugh, subjects taught and session type fields to tutor applications table

Revision ID: 9d0fa521a088
Revises: 3d3bc4080eb9
Create Date: 2026-06-23 10:52:13.401308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0fa521a088'
down_revision = '3d3bc4080eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_taught', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('subjects_taught', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('session_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('experience_proof_url', sa.String(length=255), nullable=False))
        batch_op.drop_column('cv_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('experience_proof_url')
        batch_op.drop_column('session_type')
        batch_op.drop_column('subjects_taught')
        batch_op.drop_column('level_taught')

    # ### end Alembic commands ###
