"""removed parent_name field from user table

Revision ID: d3bcb41b6c36
Revises: 4dca2d6ccb1f
Create Date: 2026-06-13 18:48:52.204538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bcb41b6c36'
down_revision = '4dca2d6ccb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('parent_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
