"""studeuser's student/child deleted when user deleted

Revision ID: d9a3b9d94389
Revises: d53d6fba4e77
Create Date: 2026-06-19 12:24:30.640802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a3b9d94389'
down_revision = 'd53d6fba4e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_student_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('bookings_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('students_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('students_parent_id_fkey'), 'users', ['parent_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_parent_id_fkey'), 'users', ['parent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('bookings_student_id_fkey'), 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
