"""reexperience_proof_url nullable

Revision ID: dbe66db7a53c
Revises: 92e687837054
Create Date: 2026-06-23 13:43:27.655448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe66db7a53c'
down_revision = '92e687837054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.alter_column('experience_proof_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_applications', schema=None) as batch_op:
        batch_op.alter_column('experience_proof_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
