"""removed billing start and billing end and also renmaed created at to paid at in paymnets table

Revision ID: ed751e22f26d
Revises: d3bcb41b6c36
Create Date: 2026-06-15 11:59:39.209523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed751e22f26d'
down_revision = 'd3bcb41b6c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('billing_period_end')
        batch_op.drop_column('created_at')
        batch_op.drop_column('billing_period_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_period_start', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_period_end', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
