"""admoved disablities_or_notes field to bookings

Revision ID: f289876f7e61
Revises: d9a3b9d94389
Create Date: 2026-06-22 11:34:42.540064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f289876f7e61'
down_revision = 'd9a3b9d94389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabilities_or_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('disabilities_or_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabilities_or_notes', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('disabilities_or_notes')

    # ### end Alembic commands ###
